forge "http://forge.puppetlabs.com"

mod 'puppetlabs-apt', '4.5.1'

mod 'puppetlabs-apache',
	:git	=> "http://github.com/puppetlabs/puppetlabs-apache.git"
  
mod 'puppetlabs-mysql',
	:git	=> "http://github.com/puppetlabs/puppetlabs-mysql.git"
	
mod 'puppetlabs-sqlite',
	:git	=> "http://github.com/puppetlabs/puppetlabs-sqlite.git"

mod 'jlondon-phpmyadmin', '1.3.0'

mod 'puppet-nodejs', '5.0.0'
